server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EricRaw/myspringcloud-config.git
          search-paths:
            - myspringcloud-config
          skip-ssl-validation: true
          username: ericraw
          password: Ll17665003393.
      label: main
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
